<a href="https://colab.research.google.com/github/Rithwik-Minfy/Data-AI_Assignment_1/blob/main/Data%2BAI_Assignment_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Data + AI Assignment 1**

**Subramanya Rithwik Jakka**

Import pandas library

In [34]:
import pandas as pd

Load a CSV file

In [35]:
df1 = pd.read_csv("oecd_bli_2015.csv", thousands=',')

Display first 5 rows

In [36]:
df1.head()

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
0,AUS,Australia,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.1,E,Estimated value
1,AUT,Austria,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.0,NaN,NaN
2,BEL,Belgium,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,2.0,NaN,NaN
3,CAN,Canada,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.2,NaN,NaN
4,CZE,Czech Republic,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.9,NaN,NaN

Find missing values in DataFrame and count them coulum-wise

In [37]:
df1.isnull().sum()

LOCATION                    0
Country                     0
INDICATOR                   0
Indicator                   0
MEASURE                     0
Measure                     0
INEQUALITY                  0
Inequality                  0
Unit Code                   0
Unit                        0
PowerCode Code              0
PowerCode                   0
Reference Period Code    3292
Reference Period         3292
Value                       0
Flag Codes               2172
Flags                    2172
dtype: int64

Filter rows in a DataFrame where a column Value > 100

In [38]:
df1[df1["Value"]>100]

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
327,AUS,Australia,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,31588.0,NaN,NaN
328,AUT,Austria,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,31173.0,NaN,NaN
329,BEL,Belgium,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,28307.0,NaN,NaN
330,CAN,Canada,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,29365.0,NaN,NaN
331,CZE,Czech Republic,IW_HADI,Household net adjusted disposable income,L,Value,TOT,Total,USD,US Dollar,0,units,NaN,NaN,18404.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1743,EST,Estonia,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,503.0,NaN,NaN
1744,ISR,Israel,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,415.0,NaN,NaN
1745,RUS,Russia,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,436.0,NaN,NaN
1746,SVN,Slovenia,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,454.0,NaN,NaN
1747,OECD,OECD - Total,ES_STCS,Student skills,L,Value,LW,Low,AVSCORE,Average score,0,units,NaN,NaN,452.0,NaN,NaN

Group a DataFrame by Country column and calculate the mean of each group

In [39]:
country_mean = df1.groupby("Country")['Value'].mean()
country_mean

Country
Australia           6267.896073
Austria             6019.059822
Belgium             7257.838220
Brazil              1994.952908
Canada              6708.151509
Chile               2755.229627
Czech Republic      2786.791761
Denmark             5735.051600
Estonia             2222.269720
Finland             4493.590157
France              5618.577255
Germany             6012.104128
Greece              3022.010949
Hungary             2503.221751
Iceland             5785.920712
Ireland             5166.357437
Israel              4783.771546
Italy               5242.214604
Japan               6382.745840
Korea               4113.501405
Luxembourg          7464.177342
Mexico              2047.348742
Netherlands         6964.230548
New Zealand         4281.938270
Norway              4947.473186
OECD - Total        4451.821302
Poland              2677.680974
Portugal            3581.125497
Russia              2467.332744
Slovak Republic     2419.655631
Slovenia            3558.214961
Spain               4167.375201
Sweden              5947.034454
Switzerland         8558.713982
Turkey              1859.787289
United Kingdom      5985.486437
United States      10622.746153
Name: Value, dtype: float64

Sort a DataFrame by multiple rows (first by Country ascending, then by Inequality ascending and then by Value Descending)

In [40]:
sorted_by_multi_cols = df1.sort_values(by=["Country","Inequality","Value"],ascending=[True,True,False])
sorted_by_multi_cols

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags
1211,AUS,Australia,JE_PEARN,Personal earnings,L,Value,HGH,High,USD,US Dollar,0,units,NaN,NaN,63976.000000,E,Estimated value
436,AUS,Australia,IW_HADI,Household net adjusted disposable income,L,Value,HGH,High,USD,US Dollar,0,units,NaN,NaN,62627.000000,E,Estimated value
1674,AUS,Australia,ES_STCS,Student skills,L,Value,HGH,High,AVSCORE,Average score,0,units,NaN,NaN,559.000000,NaN,NaN
2299,AUS,Australia,CG_VOTO,Voter turnout,L,Value,HGH,High,PC,Percentage,0,units,NaN,NaN,94.000000,E,Estimated value
1396,AUS,Australia,SC_SNTWS,Quality of support network,L,Value,HGH,High,PC,Percentage,0,units,NaN,NaN,93.000000,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
320,USA,United States,HO_NUMR,Rooms per person,L,Value,WMN,Women,RATIO,Ratio,0,units,NaN,NaN,2.400000,E,Estimated value
3062,USA,United States,PS_REPH,Homicide rate,L,Value,WMN,Women,RATIO,Ratio,0,units,NaN,NaN,2.200000,NaN,NaN
1018,USA,United States,JE_LTUR,Long-term unemployment rate,L,Value,WMN,Women,PC,Percentage,0,units,NaN,NaN,1.791424,NaN,NaN
2951,USA,United States,PS_SFRV,Assault rate,L,Value,WMN,Women,PC,Percentage,0,units,NaN,NaN,1.300000,NaN,NaN
102,USA,United States,HO_BASE,Dwellings without basic facilities,L,Value,WMN,Women,PC,Percentage,0,units,NaN,NaN,0.100000,E,Estimated value

Add a new column to a DataFrame that is transformation of existing columns. (Double_Value which is transformation of Value by multiplying with 2)

In [41]:
df1["Double_of_Value"] = df1["Value"]*2
df1

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,PowerCode Code,PowerCode,Reference Period Code,Reference Period,Value,Flag Codes,Flags,Double_of_Value
0,AUS,Australia,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.10,E,Estimated value,2.20
1,AUT,Austria,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,1.00,NaN,NaN,2.00
2,BEL,Belgium,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,2.00,NaN,NaN,4.00
3,CAN,Canada,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.20,NaN,NaN,0.40
4,CZE,Czech Republic,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,0,units,NaN,NaN,0.90,NaN,NaN,1.80
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3287,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,units,NaN,NaN,14.43,NaN,NaN,28.86
3288,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,units,NaN,NaN,14.24,E,Estimated value,28.48
3289,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,units,NaN,NaN,14.75,E,Estimated value,29.50
3290,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,units,NaN,NaN,14.12,NaN,NaN,28.24
3291,OECD,OECD - Total,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,0,units,NaN,NaN,14.74,NaN,NaN,29.48

Load another CSV file

In [42]:
df2 = pd.read_csv("gdp_per_capita.csv", thousands=',')

Merge two DataFrames (df1 and df2) on Country column by Inner Join

In [43]:
country_inner_merged = pd.merge(df1,df2,on="Country",how="inner")
country_inner_merged

,LOCATION,Country,INDICATOR,Indicator,MEASURE,Measure,INEQUALITY,Inequality,Unit Code,Unit,...,Value,Flag Codes,Flags,Double_of_Value,Subject Descriptor,Units,Scale,Country/Series-specific Notes,2015,Estimates Start After
0,AUS,Australia,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,1.10,E,Estimated value,2.20,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",50961.87,2014.0
1,AUT,Austria,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,1.00,NaN,NaN,2.00,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",43724.03,2015.0
2,BEL,Belgium,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,2.00,NaN,NaN,4.00,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",40106.63,2014.0
3,CAN,Canada,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,0.20,NaN,NaN,0.40,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",43331.96,2015.0
4,CZE,Czech Republic,HO_BASE,Dwellings without basic facilities,L,Value,TOT,Total,PC,Percentage,...,0.90,NaN,NaN,1.80,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",17256.92,2015.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3213,CHL,Chile,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.16,E,Estimated value,28.32,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",13340.91,2014.0
3214,EST,Estonia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.43,NaN,NaN,28.86,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",17288.08,2014.0
3215,ISR,Israel,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.24,E,Estimated value,28.48,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",35343.34,2015.0
3216,RUS,Russia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.75,E,Estimated value,29.50,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",9054.91,2015.0
3217,SVN,Slovenia,WL_TNOW,Time devoted to leisure and personal care,L,Value,WMN,Women,HOUR,Hours,...,14.12,NaN,NaN,28.24,"Gross domestic product per capita, current prices",U.S. dollars,Units,"See notes for: Gross domestic product, curren...",20732.48,2015.0